[package]
name = "wallet-app"
version = "0.1.0"
authors = ["Christian Mayer <christian@fox21.at>"]
edition = "2018"

[dependencies]
wallet-lib = { path = "wallet_lib" }
clap = "2.33.0"

[workspace]
members = [
    "wallet_lib",
]
